

파이썬 머신러닝 완벽 가이드

1주차



## [1] 파이썬 기반의 머신러닝과 생태계 이해
### 03. 넘파이

* 넘파이 : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지


### [넘파이 ndarray 개요]


In [ ]:
import numpy as np

* 넘파이의 기반 데이터 타입 :  ndarray
* 넘파이 array() 함수 : 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


* 차원이 달라서 오류가 발생하는 경우가 빈번하여 차원 확인을 하는 것이 중요

In [ ]:
# ndarray.ndim을 통해 각 array의 차원 확인

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'. format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### [ndarrary의 데이터 타입]

* ndarray 내의 데이터 타입은 같은 데이터 타입만 가능

In [ ]:
# dtype 속성으로 ndarrary 내의 데이터 타입 확인하기

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
# int형과 string 형이 섞여 있는 리스트
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 숫자형 값(int)가 문자열로 변환

# int형과 float 형이 섞여 있는 리스트
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # int가 float으로 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


* astype() 를 이용하여 ndarray 내 데이터값의 타입 변경
(메모리 절약을 위해 이용)

In [ ]:
# int32형 데이터를 float64로 변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float64를 int32로 변경
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

# float을 int형으로 변경할 때 소수점 이하는 당연히 모두 없어짐
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### [ndarray를 편리하게 생성하기 - arange, zeros, ones]

* 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우에 사용

In [ ]:
# 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

# arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
#zeros()
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones()
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### [ndarray의 차원과 크기를 변경하는 reshape()]



* reshape() : ndarray를 특정 차원 및 크기로 변환

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* 지정된 사이즈로 변경이 불가하면 오류가 발생

In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

* reshape()를 실전에서 더욱 효율적으로 사용하는 경우 : 인자로 -1을 적용하는 경우
* 인자로 -1을 사용 : 원래 ndarray와 호환되는 새로운 shape로 변환

In [ ]:
# 인자로 -1 적용

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # 칼럼은 5로 고정, 로우를 자동으로 생성해 변환하라
print('array2 shape:', array2.shape) # 2x5

array3 = array1.reshape(5,-1) # 로우는 5로 고정, 칼럼을 자동으로 생성해 변환하라
print('array3 shape:', array3.shape) # 5x2

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# 변경할 수 없으면 에러 발생

array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

* reshape (-1,1)
* 원본 ndarray가 어떤 형태라도 2차원이고 1개의 칼럼을 가지게 변환

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### [넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)]

1. 특정한 데이터만 추출
2. 슬라이싱 (Slicing)
3. 팬시 인덱싱 (Fancy Indexing)
4. 불린 인덱싱 (Boolean Indexing)

#### 1) 단일 값 추출
* 한 개의 데이터만 추출

In [ ]:
# 1부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1 :', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


* 인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출

In [ ]:
# 인덱스 -1은 맨 뒤의 데이터값

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


* 단일 인덱스를 이용해 ndarray 내의 데이터값을 간단히 수정

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


* 다차원 ndarray에서 단일 값을 추출

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값;', array2d[0,0])
print('(row=0, col=1) index 가리키는 값;', array2d[0,1])
print('(row=1, col=0) index 가리키는 값;', array2d[1,0])
print('(row=2, col=2) index 가리키는 값;', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값; 1
(row=0, col=1) index 가리키는 값; 2
(row=1, col=0) index 가리키는 값; 4
(row=2, col=2) index 가리키는 값; 9


* axis 1 : 칼럼 방향의 축
[row=0, col=1] == [axis0=0, axis1=1]

#### 2) 슬라이싱
* ':' 기호를 이용해 연속한 데이터를 슬라이실해서 추출

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


* (1) ':' 기호 앞에 시작 인덱스를 생략 : 맨 처음 인덱스인 0으로 간주
* (2) ':' 기호 뒤에 종료 인덱스를 생략 : 맨 마지막 인덱스로 간주
* (3) ':' 기호 앞/뒤에 시작/종료 인덱스를 생략 : 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


* 2차원 ndarray에서 슬라이싱

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2,0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3,0:3])
print('array2d[1:3, :]\n', array2d[1:3,:])
print('array2d[:, :]\n', array2d[:,:])
print('array2d[:2, 1:]\n', array2d[:2,1:])
print('array2d[:2, 0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


* 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0]:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0]: (3,) array2d[1] shape: (3,)


#### 3) 팬시 인덱싱
* 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#### 4) 불린 인덱싱
* 조건 필터링과 검색을 동시에 할 수 있어 자주 사용되는 인덱싱 방식
* loop/if else 문보다 훨씬 간단하게 구현 가능

In [ ]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 을 적용
array3= array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


* 조건 필터링이 이처럼 간단한 이유

In [ ]:
# 넘파이 ndarray 객체에 조건식을 할당하면

array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
# False 가 있는 인덱스는 무시함

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
# 직접 인덱스 집합을 만들어 대입한 것과 동일

indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


* step1 : array1d > 5 와 같이 ndarray의 필터링 조건을 [] 안에 기재
* step2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장
* step3 : 저장된 인덱스 데이터 세트로 ndarray 조회

### [행렬의 정렬 - sort()와 argsort()]



#### 1) 행렬 정렬
* np.sort() : 넘파이에서 sort()를 호출하는 방식, 원 행렬을 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
* ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식, 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 :', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


* 내림차순으로 정렬 : [::-1]

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


#### 2) 정렬된 행렬의 인덱스를 반환하기

* np.argsort() : 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때, 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [ ]:
# np.argsort()를 이용해 원본 행렬의 정렬 시 행렬 인덱스 값 구하기

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
# 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하기

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


* argsort()의 활용

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### [선형대수 연산 - 행렬 내적과 전치 행렬 구하기]

#### 1) 행렬 내적 (행렬 곱)
* np.dot() : 두 행렬의 내적 계산

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 2) 전치 행렬
* 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
* transpose() : 전치 행렬 구하기

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
