# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
size_of_null_vector = null_vector.nbytes
print(size_of_null_vector)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector2 = np.sort(vector1)[::-1]
print(vector2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1 = np.arange(9)
array2 = array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(array)[0]

print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array = np.random.random((3,3,3))
print(array)

[[[0.30784504 0.54151428 0.78932054]
  [0.0836618  0.84543133 0.02455794]
  [0.70446478 0.90797569 0.27579515]]

 [[0.16921837 0.9027283  0.30558945]
  [0.33323237 0.13480251 0.41924805]
  [0.45819628 0.32217158 0.40421811]]

 [[0.29517759 0.00497584 0.96738931]
  [0.28887832 0.94466313 0.46303532]
  [0.41438306 0.54502311 0.1329707 ]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array1 = np.random.random((10,10))
print('Array with random values : \n', array1)

array2 = np.sort(array1)

min_value = array2[0,0]
max_value = array2[9,9]

print('Minimum Value :' , min_value)
print('Maximum Value :' , max_value)

Array with random values : 
 [[0.20177303 0.72406707 0.14637234 0.25333987 0.07944423 0.91597037
  0.94383935 0.66899283 0.95003988 0.19952599]
 [0.59532429 0.29444228 0.64229989 0.99490742 0.57238595 0.00884812
  0.81568015 0.77783429 0.10829611 0.58467119]
 [0.81318271 0.20771226 0.25538475 0.49337046 0.36641213 0.96548231
  0.93030387 0.7502009  0.80589406 0.63241684]
 [0.11926371 0.59864164 0.99905405 0.31364123 0.11715663 0.06029749
  0.628276   0.36274894 0.37453833 0.98070799]
 [0.32597603 0.00135299 0.04271317 0.59186556 0.46215248 0.40410786
  0.41478785 0.30274169 0.4047678  0.36994059]
 [0.36628301 0.54193315 0.30311243 0.99397494 0.68869938 0.11161362
  0.91236366 0.87132229 0.23346392 0.99998285]
 [0.73417645 0.54449433 0.47298679 0.95375036 0.41016844 0.69287559
  0.66421552 0.15005836 0.9712872  0.987688  ]
 [0.08315201 0.74121695 0.36519374 0.71118879 0.44042086 0.01703453
  0.31078413 0.33531183 0.41825332 0.6393395 ]
 [0.09236597 0.86126062 0.23111215 0.11532    0.617

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_vec = np.random.random(30)
mean_val = np.mean(random_vac)

print(random_vec)
print('Mean Value :', mean_val)

[0.48529719 0.15294904 0.2099591  0.42933335 0.09440001 0.86239868
 0.79834513 0.47959326 0.3457285  0.21440896 0.34705569 0.62873863
 0.93282901 0.92126489 0.33693264 0.33056076 0.64483372 0.62524007
 0.37975384 0.76403653 0.20208557 0.46784222 0.73885545 0.42501557
 0.0889886  0.89047103 0.17069277 0.13817084 0.1691394  0.3790585 ]
Mean Value : 0.5707026251576343


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array_border = np.zeros((5,8))

array_border[0,:] = 1
array_border[:,0] = 1
array_border[-1,:] = 1
array_border[:,-1] = 1

print(array_border)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array = np.zeros((5,5))

for i in range(1,5) :
  array[i,i-1] = 1

for i in range(2,5) :
  array[i,i-2] = 2

for i in range(3,5) :
  array[i,i-3] = 3

for i in range(4,5) :
  array[i,i-4] = 4

print(array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array = np.zeros((8,8))

array[::2, ::2] = 1
array[1::2, 1::2] = 1

print(array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random_matrix = np.random.random((5,5))

mean_val = random_matrix.mean()
sd_val = np.sqrt(random_matrix.var())

nor_matrix = (random_matrix - mean_val)/sd_val
print(nor_matrix)

[[-0.62880518  1.43722988  1.54676552  1.2141437   0.58766218]
 [-1.43587404  1.60432639  0.66521698  0.79597715 -0.0618951 ]
 [-1.45381509  0.89532399 -1.40339911 -0.52851753  1.27435277]
 [-1.00313764 -0.09226806 -0.25364384 -0.5492537  -0.41995548]
 [-0.19568891 -1.1122205   1.05359582 -0.91057205 -1.02554811]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
RGBA_dtype = np.dtype([('R', np.ubyte),('G', np.ubyte),('B', np.ubyte),('A', np.ubyte)])
print(RGBA_dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

np.dot(A, B)


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [8]:
arr = np.array([1,3,5,7,8,9,10])

arr[(arr >= 3) & (arr <= 8)] *= -1

print(arr)


[ 1 -3 -5 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [9]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

# 어렵

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [10]:
Z = np.array([1,2,3,4,5,6])

Z**Z

array([    1,     4,    27,   256,  3125, 46656])

In [11]:
2 << Z >> 2

array([ 1,  2,  4,  8, 16, 32])

In [12]:
Z <- Z

array([False, False, False, False, False, False])

In [13]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j])

In [14]:
Z/1/1

array([1., 2., 3., 4., 5., 6.])

In [15]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
np.array(0) / np.array(0)

<ipython-input-16-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [18]:
np.array(0) // np.array(0)

<ipython-input-18-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [17]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-17-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [21]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
print(np.intersect1d(Z1, Z2))

[0 3 8 5 6 9 4 9 2 2]
[3 2 2 1 0 4 6 6 9 6]
[0 2 3 4 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [22]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-22-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [23]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [26]:
Z = np.arange('2016-07-01','2016-08-01', dtype = 'datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [30]:
A = np.array([1,2,3])
B = np.array([11,12,13])

add_AB = np.add(A,B)
div_A2 = np.divide(-A, 2)
result = np.multiply(add_AB, div_A2)

print(result)

[ -6. -14. -24.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [32]:
array = np.random.random(10) * 100 #

arr_int1 = array - (array % 1)
arr_int2 = array // 1

print(array)

print(arr_int1)
print(arr_int2)

[10.89441387  5.06253145 27.05768804 79.3912151  19.09035097 33.27824595
 84.04932764  3.85025898 83.9533671  63.23132264]
[10.  5. 27. 79. 19. 33. 84.  3. 83. 63.]
[10.  5. 27. 79. 19. 33. 84.  3. 83. 63.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
matrix = np.arange(5)
matrix = np.tile(matrix, (5, 1))

print(matrix)

Matrix using NumPy:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [34]:
Z = np.random.randint(0, 10, (3, 3))

print(Z)

[[5 5 3]
 [8 3 3]
 [2 9 3]]


In [38]:
# column 1

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[1 0 2]
1번째 열을 기준으로 정렬된 배열:
[[8 3 3]
 [5 5 3]
 [2 9 3]]


In [ ]:
# column 2

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

In [ ]:
# column 3

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])